;==============================================================================;
;                                                                              ;
;     System Information Library: connect include files with subroutines.      ;
;                                                                              ;
;==============================================================================;

include 'load_inf.inc'
include 'load_kmd.inc'
include 'sysinfo_user_mode.inc'
include 'sysinfo_kernel_mode.inc'
