;==============================================================================;
;                                                                              ;
;        This performance patterns used in the "Math" benchmark scenario.      ;
;           Library of performance patterns for mathematics benchmarks:        ;
;               constants and variables with pre-defined values.               ;
;                                                                              ;
;==============================================================================;


