;==============================================================================;
;                                                                              ;
;   Library for memory and threads management, include adjust measurements:    ;
;               constants and variables with pre-defined values.               ;
;                                                                              ;
;==============================================================================;


