;==============================================================================;
;                                                                              ;
;                  This performance patterns used in the                       ; 
;                    "Run", "Draw" benchmark scenarios.                        ;
;          Library of performance patterns for bandwidth measurement:          ;
;                   variables without pre-defined values.                      ;
;                                                                              ;
;==============================================================================;
; Reserved. This data type for this module yet not used.