;------------------------------------------------------------------------------;
;                Registers and memory dump subroutines library:                ;
;                       global used data definitions.                          ;
;------------------------------------------------------------------------------;

REGISTER_NAME_COLOR   EQU  FOREGROUND_RED + FOREGROUND_GREEN + FOREGROUND_INTENSITY
REGISTER_VALUE_COLOR  EQU  FOREGROUND_RED + FOREGROUND_GREEN + FOREGROUND_BLUE + FOREGROUND_INTENSITY

DUMP_ADDRESS_COLOR    EQU  FOREGROUND_GREEN + FOREGROUND_INTENSITY
DUMP_DATA_COLOR       EQU  FOREGROUND_RED + FOREGROUND_GREEN + FOREGROUND_BLUE + FOREGROUND_INTENSITY
