;------------------------------------------------------------------------------;
;                                                                              ;
;   Library for memory and threads management, include adjust measurements:    ;
;                    connect include files with subroutines.                   ;
;                                                                              ;
;------------------------------------------------------------------------------;


