;------------------------------------------------------------------------------;
;                                                                              ;
;   Library for memory and threads management, include adjust measurements:    ;
;                   variables without pre-defined values.                      ;
;                                                                              ;
;------------------------------------------------------------------------------;


