;------------------------------------------------------------------------------;
;                                                                              ;
;   Library for memory and threads management, include adjust measurements:    ;
;                               data definitions.                              ;
;                                                                              ;
;------------------------------------------------------------------------------;


