;------------------------------------------------------------------------------;
;                  Target fragment for debug, this part is:                    ;
;              globally used variables without pre-defined values.             ;     
;------------------------------------------------------------------------------;

SystemInfo              SYSTEM_INFO  ?
_SetThreadAffinityMask  DQ           ?
ProcessorCounter        DD           ?
AffinityMask            DQ           ?
OriginalAffinityMask    DQ           ?